commit_message: 'Chore: Localization updates for %original_file_name% [no ci]'
append_commit_message: true
preserve_hierarchy: true
files:
  - source: /src/Resources/Localization/Plugin/*_Localizable.json
    translation: /%original_path%/%two_letters_code%.json
  - source: /src/Resources/Localization/Duty/en/A Realm Reborn/AllianceRaids
    translation: /src/Resources/Localization/Duty/%two_letters_code%/A Realm Reborn/AllianceRaids/%original_file_name%
  - source: src/Resources/Localization/Duty/en/A Realm Reborn/Dungeons/
    translation: src/Resources/Localization/Duty/%two_letters_code%/A Realm Reborn/Dungeons/%original_file_name%
  - source: src/Resources/Localization/Duty/en/A Realm Reborn/Trials
    translation: src/Resources/Localization/Duty/%two_letters_code%/A Realm Reborn/Trials/%original_file_name%
  - source: /src/Resources/Localization/Duty/en/Heavensward/AllianceRaids
    translation: /src/Resources/Localization/Duty/%two_letters_code%/Heavensward/AllianceRaids/%original_file_name%
